name: Release

#on:
#  push:
#    branches:
#      - main*

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'bmir-radx-bot[bot]' }}
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ vars.BMIR_RADX_BOT_APP_ID }}
          private-key: ${{ secrets.BMIR_RADX_BOT_APP_PRIVATE_KEY }}
      - uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          ref: ${{ github.head_ref }}
      - name: Set up Maven Central Repository
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'adopt'
      - name: Bump version
        id: bump
        uses: mickem/gh-action-bump-maven-version@v1
      - name: Build and Publish package
        run: mvn --batch-mode package deploy
      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.bump.outputs.tag }}
          generate_release_notes: true
